DROP TABLE IF EXISTS animals;
DROP TABLE IF EXISTS species;

CREATE TABLE animals (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    animal_id TEXT NOT NULL,
    animal TEXT NOT NULL
);

CREATE TABLE species (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    animal_id TEXT NOT NULL,
    species TEXT NOT NULL
);

